---
- name: Setting up LAMP Website
  hosts: localhost
  become: yes #to become root user similar to sudo SU
  tasks:
    - name: latest version of all required packages installed
      apt:
        name: firewalld
      register: apache 
    - name: printing output of package installation task
      debug: 
        msg: '{{ apache }}'
    # - name: installing a package
    #   shell: sudo apt install firewalld
        